export enum hdr {
    accept_contact/*!< Accept-Contact header */,
    accept_language/*!< Accept-Language header field */,
    accept/*!< Accept header field */,
    allow_events /*!< Allow-Events header */,
    allow /*!< Allow header field */,
    authorization/*!< Authorization header field */,
    callid /*!< Call-Id header field */,
    callinfo /*!< Call-Info header field*/,
    contact /*!< Contact header field */,
    content_disposition /*!< Content-Disposition hdr field */,
    content_encoding /*!< Content-Encoding header */,
    content_length /*!< Content-Length header field */,
    content_type /*!< Content-Type header field */,
    cseq/*!< CSeq header field */,
    date /*!< Date header field */,
    diversion /*!< Diversion header field */,
    eoh /*!< End of message header (lastid + 1) */,
    error /*!< Error while parsing */,
    event/*!< Event header field */,
    expires /*!< Expires header field */,
    from /*!< From header field */,
    identity_info /*!< Identity-info header field */,
    identity /*!< Identity header field */,
    max_forwards /*!< MaxForwards header field */,
    min_expires /*!< Min-Expires header */,
    min_se /*!< Min-SE */,
    organization /*!< Organization header field */,
    other /*!< Some other header field */,
    pai /*!< P-Asserted-Identity header field*/,
    path /*!< Path header field */,
    ppi /*!< P-Preferred-Identity header field*/,
    priority /*!< Priority header field */,
    privacy /*!< Privacy header field */,
    proxy_auth /*!< Proxy-Authorization hdr field */,
    proxy_authenticate /*!< Proxy-Authenticate header field */,
    proxy_require/*!< Proxy-Require header field */,
    reason/**< Reason header field */,
    record_route /*!< Record-Route header field */,
    refer_to /*!< Refer-To header fiels */,
    referred_by /*!< Referred-By header */,
    reject_contact /*!< Reject-Contact header */,
    request_disposition/*!< Request-Disposition header */,
    require /*!< Require header */,
    retry_after /*!< Retry-After header field */,
    route /*!< Route header field */,
    rpid /*!< Remote-Party-ID header field */,
    server /*!< Server header field */,
    session_expires/*!< Session-Expires header */,
    sip_if_match /*!< SIP-If-Match header field */,
    subject /*!< Subject header field */,
    subscription_state /*!< Subscription-State */,
    supported /*!< Supported  header field */,
    to/*!< To header field */,
    unsupported /*!< Unsupported header field */,
    user_agent/*!< User-Agent header field */,
    via /*!< Via header field */,
    via1/*!< First Via header field */,
    via2/*!< only used as flag */,
    www_authenticate /*!< WWW-Authenticate header field */,
};

export const hdr_type_f = {
    [hdr.accept_contact]: 'Accept-Contact: ',
    [hdr.accept_language]: 'Accept-Language: ',
    [hdr.accept]: 'Accept: ',
    [hdr.allow_events]: 'Allow: ',
    [hdr.allow]: 'Allow: ',
    [hdr.authorization]: 'Authorization: ',
    [hdr.callid]: 'Call-ID: ',
    [hdr.callinfo]: 'DCall-Infoate: ',
    [hdr.contact]: 'Contact: ',
    [hdr.content_disposition]: 'Content-Disposition: ',
    [hdr.content_encoding]: 'Content-Encoding: ',
    [hdr.content_length]: 'Content-Length: ',
    [hdr.content_type]: 'Content-Type: ',
    [hdr.cseq]: 'CSeq: ',
    [hdr.date]: 'Date: ',
    [hdr.diversion]: 'Diversion: ',
    [hdr.event]: 'Event: ',
    [hdr.expires]: 'Expires: ',
    [hdr.from]: 'From: ',
    [hdr.identity_info]: 'Identity-info: ',
    [hdr.identity]: 'Identity: ',
    [hdr.max_forwards]: 'Max-Forwards: ',
    [hdr.min_expires]: 'Min-Expires: ',
    [hdr.min_se]: 'Min-SE: ',
    [hdr.organization]: 'Organization: ',
    [hdr.pai]: 'P-Asserted-Identity: ',
    [hdr.path]: 'Path: ',
    [hdr.ppi]: 'P-Preferred-Identity: ',
    [hdr.priority]: 'Priority: ',
    [hdr.privacy]: 'Privacy: ',
    [hdr.proxy_auth]: 'Proxy-Authorization: ',
    [hdr.proxy_authenticate]: 'Proxy-Authenticate: ',
    [hdr.proxy_require]: 'Proxy-Require: ',
    [hdr.reason]: 'Reason: ',
    [hdr.record_route]: 'Record-Route: ',
    [hdr.refer_to]: 'Refer-To: ',
    [hdr.referred_by]: 'Referred-By: ',
    [hdr.reject_contact]: 'Reject-Contact: ',
    [hdr.request_disposition]: 'Request-Disposition: ',
    [hdr.require]: 'Require: ',
    [hdr.retry_after]: 'Retry-After: ',
    [hdr.route]: 'Route: ',
    [hdr.rpid]: 'Remote-Party-ID: ',
    [hdr.server]: 'Server: ',
    [hdr.session_expires]: 'Session-Expires: ',
    [hdr.sip_if_match]: 'SIP-If-Match: ',
    [hdr.subject]: 'Subject: ',
    [hdr.subscription_state]: 'Subscription-State: ',
    [hdr.supported]: 'Supported: ',
    [hdr.to]: 'To: ',
    [hdr.unsupported]: 'Unsupported: ',
    [hdr.user_agent]: 'User-Agent: ',
    [hdr.via]: 'Via: ',
    [hdr.www_authenticate]: 'WWW-Authenticate: ',
}